@startuml PBL_JAVA

abstract class Pessoa{
    -nome: String
    -endereco: String
    -telefone: String
    -id: Integer
    -senha: String
    +logar(objeto: Pessoa) : Pessoa
    +mudarNome(objeto: Pessoa) : Pessoa
    +mudarEndereco(objeto: Pessoa) : Pessoa
    +mudarTelefone(objeto: Pessoa) : Pessoa
    +pesquisarLivro(objeto: Livro) : Livro
}

class Leitor {
    -statusConta: Boolean
    -diasdeMulta: int
    -historicoEmprestimos: List<Emprestimo>
    +reservarLivro(objeto: Livro) : boolean
    +renovarEmprestimo(objeto: Livro, objeto: Emprestimo) : boolean
}

class Bibliotecario{
    +registrarEmprestimo(objeto: Livro, objeto: Emprestimo) : boolean
    +registrarDevolucao(objeto: Livro, , objeto: Emprestimo) : boolean
    +registrarLivro(objeto: Livro) : Livro
}

class Administrador{
    +removerLivro(objeto: Livro) : Livro
    +editarLivro(objeto: Livro) : Livro
    +registrarUsuario(objeto: Usuario) : Usuario
    +bloquearUsuario(objeto: Usuario) : Usuario
    +gerarMulta(objeto: Emprestimo)
    +gerarEstatistica(objeto: Livro) : void
    +relatorioDeUsuarios(objeto: Usuario) : void
}

abstract class Funcionario{

}

class Livro{
    -título: String
    -autor: String
    -editora: String
    -isbn: String
    -anoDePublicação: String
    -categoria: CategoriaLivro
    -editora: String
    -localização: String
    -statusReserva: Boolean
    -livroID: int
    -disponibilidade: boolean
    +mudarNome(objeto: Livro) : Livro
    +mudarAutor(objeto: Livro) : Livro
    +mudarCategoria(objeto: Livro) : Livro
    +mudarEditora(objeto: Livro) : Livro
    +mudarAnoDepublicacao(objeto: Livro) : Livro
    +mudarLocalizacao(objeto: Livro) : Livro
}

class Emprestimo{
    -dataEmprestimo: LocalDate
    -dataDevolucao: LocalDate
    -infoUsuario: Usuario
    -infoLivro: Livro
    -atraso: int
    -naoDevolvido: boolean
    -NUMERO_RENOVACOES: int = 2 (final)
    +renovarEmprestimo(objeto: Livro, objeto: Emprestimo) : void
    +devolucaoEmprestimo(objeto: Livro, objeto: Emprestimo) : void
}

class Reserva{
    -reservaID: Integer
    -livroReservado: Livro
    -Leitor: Leitor
}

Emprestimo --> Livro : usa
Emprestimo --> Leitor : usa
Reserva --> Livro : usa
Reserva --> Leitor : usa
Administrador --> Emprestimo : usa
Bibliotecario --> Emprestimo : usa

Emprestimo "1"--"1" Leitor
Reserva "1"--"1" Leitor

Funcionario <|-- Bibliotecario : é um
Funcionario <|-- Administrador : é um
Funcionario <|-- Pessoa
Pessoa <|-- Leitor : é um

@enduml